// Angular-List/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'Angular-List';
}

<div class="header">
	<div class="topline">
		Made by Adrian Przybilla
	</div>
	<div class="welcome h1">
		Welcome to my Angular example
	</div>
</div>

<div class="content">
	<st-list-factory [list]="list$ | async"></st-list-factory>
	<st-list-static [list]="list$ | async"></st-list-static>
</div>

// react-list/src/App.tsx
import React from 'react';
import './App.scss';
import List from './list/List';

class App extends React.Component {
	render() {
		return <>
			<div className="header">
				<div className="topline">
					Made by Adrian Przybilla
				</div>
				<div className="welcome h1">
					Welcome to my Angular example
				</div>
			</div>

			<div className="content">
				<List></List>
			</div >
		</>
	}

}

export default App;
